CREATE SCHEMA SEGURO_G29827867;
CREATE TABLE IF NOT EXISTS SEGURO_G29827867.PAIS (
    cod_pais SERIAL PRIMARY KEY,
    nb_pais VARCHAR(20) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS SEGURO_G29827867.CIUDAD (
    cod_ciudad SERIAL PRIMARY KEY,
    nb_ciudad VARCHAR(20) NOT NULL UNIQUE,
    cod_pais INTEGER REFERENCES SEGURO_G29827867.PAIS(cod_pais)
);
CREATE TABLE IF NOT EXISTS SEGURO_G29827867.SUCURSAL (
    cod_sucursal SERIAL PRIMARY KEY,
    nb_sucursal VARCHAR(20) NOT NULL UNIQUE,
    cod_ciudad INTEGER REFERENCES SEGURO_G29827867.CIUDAD(cod_ciudad)
);
CREATE TABLE IF NOT EXISTS SEGURO_G29827867.TIPO_PRODUCTO (
    cod_tipo_producto SERIAL PRIMARY KEY,
    nb_tipo_producto VARCHAR(20) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS SEGURO_G29827867.PRODUCTO(
    cod_producto SERIAL PRIMARY KEY,
    nb_producto VARCHAR(20) NOT NULL UNIQUE,
    descripcion VARCHAR(100) NOT NULL,
    cod_tipo_producto INTEGER REFERENCES SEGURO_G29827867.TIPO_PRODUCTO(cod_tipo_producto),
    calificacion INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS SEGURO_G29827867.CLIENTE (
    cod_cliente SERIAL PRIMARY KEY,
    nb_cliente VARCHAR(30) NOT NULL,
    ci_rif VARCHAR(10) NOT NULL UNIQUE,
    telefono VARCHAR(11) NOT NULL,
    direccion VARCHAR(30) NOT NULL,
    sexo VARCHAR(1) NOT NULL,
    email VARCHAR(50) NOT NULL,
    cod_sucursal INTEGER REFERENCES SEGURO_G29827867.SUCURSAL(cod_sucursal),
    CONSTRAINT val_sexo CHECK (sexo IN ('F','M'))
);
CREATE TABLE IF NOT EXISTS SEGURO_G29827867.EVALUACION_SERVICIO (
    cod_evaluacion_servicio SERIAL PRIMARY KEY,
    nb_descripcion VARCHAR(100) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS SEGURO_G29827867.RECOMIENDA (
    cod_cliente INTEGER REFERENCES SEGURO_G29827867.CLIENTE(cod_cliente),
    cod_evaluacion INTEGER REFERENCES SEGURO_G29827867.EVALUACION_SERVICIO(cod_evaluacion_servicio),
    cod_producto INTEGER REFERENCES SEGURO_G29827867.PRODUCTO(cod_producto),
    recomienda BOOLEAN NOT NULL,
    PRIMARY KEY (cod_cliente,cod_evaluacion,cod_producto)
);
CREATE TABLE IF NOT EXISTS SEGURO_G29827867.CONTRATO (
    nro_contrato SERIAL PRIMARY KEY,
    descrip_contrato VARCHAR(100) NOT NULL
);
CREATE TABLE IF NOT EXISTS SEGURO_G29827867.REGISTRO_CONTRATO(
    cod_cliente INTEGER REFERENCES SEGURO_G29827867.CLIENTE(cod_cliente),
    nro_contrato INTEGER REFERENCES SEGURO_G29827867.CONTRATO(nro_contrato),
    cod_producto INTEGER REFERENCES SEGURO_G29827867.PRODUCTO(cod_producto),
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    estado_contrato VARCHAR(20) NOT NULL,
    monto DECIMAL(10,2) NOT NULL,
    CONSTRAINT val_estado CHECK (estado_contrato IN ('ACTIVO','VENCIDO','SUSPENDIDO')),
    PRIMARY KEY(cod_cliente, nro_contrato, cod_producto)
);
CREATE TABLE IF NOT EXISTS SEGURO_G29827867.SINIESTRO(
    nro_siniestro SERIAL PRIMARY KEY,
    descrip_siniestro VARCHAR(100) NOT NULL
);
CREATE TABLE IF NOT EXISTS SEGURO_G29827867.REGISTRO_SINIESTRO(
    cod_cliente INTEGER REFERENCES SEGURO_G29827867.CLIENTE(cod_cliente),
    nro_contrato INTEGER REFERENCES SEGURO_G29827867.CONTRATO(nro_contrato),
    nro_siniestro INTEGER REFERENCES SEGURO_G29827867.SINIESTRO(nro_siniestro),
    fecha_siniestro DATE NOT NULL,
    fecha_respuesta DATE NOT NULL,
    rechazo BOOLEAN NOT NULL,
    monto_reconocido DECIMAL(10,2) NOT NULL,
    monto_solicitado DECIMAL(10,2) NOT NULL,
    monto DECIMAL(10,2) NOT NULL,
    PRIMARY KEY(nro_contrato, nro_siniestro, fecha_siniestro, cod_cliente)
);
